name: Rebuild points and publish 
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
       - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
       - name: Check out repository code
         uses: actions/checkout@v3
       - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
       - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
       - name: PR Build & Merge
         uses: nikhilaii93/pr-autobuild@v1.0.0-beta.1
       - name: Refresh points.js and push it     
         env:
          GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
         run: |
          cd bin && npm install && node refresh.js "$GOOGLE_KEY"
       - name: Add & Commit
         uses: EndBug/add-and-commit@v9.0.0
       - run: echo "This job's status is ${{ job.status }}."   